FROM node

WORKDIR /usr/src/

RUN npm install -g typescript
RUN npm install -g ts-node

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3001 3001

RUN npm run build

# Run node server
CMD npm start
