version: '3'
services:
    server:
        container_name: cnw-api-version-dev
        restart: unless-stopped
        build: 
            context: .
            dockerfile: dockerfile
        args:
            - PORT = 8080
        network_mode: bridge
        ports:
        - 8080:8080
        env_file:
        - .env
        volumes:
        - ./logs:/root/.pm2/logs:Z
        # - ./logs:/home/.pm2/logs:Z
        # - /Users/william/WORKSPACE/course-nccu-backend-2/logs:/usr/src/app/logs:Z
        - ./logs:/usr/src/logs:Z
    db:
        image: postgres
        environment:
        POSTGRES_USER: your_postgres_username
        POSTGRES_PASSWORD: your_postgres_password
        POSTGRES_DB: your_database_name
        volumes:
        - ./data:/var/lib/postgresql/data
